### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [mlibre/healight#1]
Hi...
I Just Came across your project and I really like the idea of the project... As a Logo Designer who has passion and Love for helping out with my Logo Design skills to contribute to very nice Open Source Projects, I want to create a Logo for your project as my Free contribution.

Sketching out some Idea concept at the moment and I will upload the concept here for you to give me your feedback or any changes you might want.

Will greatly appreciate your response...

Regards!

**Comment by mlibre** [comment]
Hi.
Oh, Thank you. it is very nice of you :rose:
Maybe it is good if I tell you some backgrounds :)
My first idea and concept about the project were "Green Life and Green planet". I realized, it starts by having a harmonic life, healthy soul and a healthy body. So I started the project, building a platform; a guidance for becoming better :)
In the heart of every guidance is knowledge, so the first part is an encyclopedia. Other phases will be:
* Online intelligence Analyzation
* Content correction mechanism
* Store
* Blog
* ....
Subjects like:
* Changing Lifestyle
* Diet Modification
* Simple and Herbal treatments for discomforts and illnesses
* Genetic Improvement
* About The Spiritual and others Worlds! :astonished: 
* etc ...
Also included by beliefs such as:
* No Animal and Plants killing :)
* Having a Green Planet
* etc ...
As I am used to designing and implementing everything modular, like this project. Others can use it for their own goals.

**Comment by chimzycash** [comment]
Thanks, for your quick response... Will finish up the idea concept and share it here for your feedback.

**Comment by chimzycash** [comment]
Hello @mlibre 
Here is the idea concept i came up with... I would love to get your feedback about the logo idea and also, you can suggest your choice of color for the logo.

![LOGO DESIGN_HEALIGHT_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/57678979-33b55c00-7622-11e9-9eee-eb834247b8fd.jpg)

![LOGO DESIGN_HEALIGHT_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/57678978-331cc580-7622-11e9-8a41-3170f2d3cfea.jpg)
![LOGO DESIGN_HEALIGHT_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/57678975-31eb9880-7622-11e9-97aa-8deaff0b5c6e.jpg)
![LOGO DESIGN_HEALIGHT_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/57678976-32842f00-7622-11e9-8006-fc5d8b461114.jpg)

![LOGO DESIGN_HEALIGHT_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/57678982-33b55c00-7622-11e9-96a7-2561840943f5.jpg)
![LOGO DESIGN_HEALIGHT_BACKGROUND_6](https://user-images.githubusercontent.com/37814297/57678986-34e68900-7622-11e9-8e49-1cb4b3c7318f.jpg)
![LOGO DESIGN_HEALIGHT_idea concept_NEW](https://user-images.githubusercontent.com/37814297/57678989-3617b600-7622-11e9-9f2b-b38bec5143bb.jpg)

**Comment by mlibre** [comment]
First of all, I am very appreciated for your time. Also, I showed the logo to my friend for feedback.
#### About Logo
* The logo is very nice.
* The way that you have shown the source of information, besides the idea of a book that comes from it.
* Especially I liked the branches.
* Implementing generator element in the center of the Logo is genius.
#### Suggestion
I and my friend were both noticed the "Generator" element before other concepts. 
The only thing is: the element guided us to industrial projects, like factories.
#### Color
In all of my projects and designs, It was always a challenge for me :)
And I am not very good at it.
Actually, I liked the color you are already using.
Also maybe we can separate the **generator** and **encyclopedia** ideas by the color. for example, a two-color gradient that starts from the generator.

**Comment by chimzycash** [comment]
I appreciate your quick feedback... 
Do you want the generator element to have a different color from the main body element

**Comment by mlibre** [comment]
Yeah, I think it could make it better.
But which colors I am not sure!
Maybe **brown** or **cream** or ...
Which color goes with it you think?

**Comment by chimzycash** [comment]
Came up with another color scheme that fully represents what the project is about...

### Light blue is associated with health, healing, tranquility, understanding, and softness.
### Dark blue represents knowledge, power, integrity, and seriousness.**

**Got this info from here:** http://www.color-wheel-pro.com/color-meaning.html


![LOGO DESIGN_HEALIGHT_BACKGROUND_1b](https://user-images.githubusercontent.com/37814297/57785189-22a34280-7729-11e9-8327-d9708c155714.jpg)
![LOGO DESIGN_HEALIGHT_BACKGROUND_2b](https://user-images.githubusercontent.com/37814297/57785190-233bd900-7729-11e9-92b4-d6c0f19c57fc.jpg)
![LOGO DESIGN_HEALIGHT_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/57785186-220aac00-7729-11e9-9046-d2f452d64668.jpg)

**Comment by mlibre** [comment]
Wow, it is really nice :cupid:
Also, it's just like the current color-theme of the platform. :star:
Thank you :rose: :tulip:

**Comment by mlibre** [comment]
Please share the PNG files, to use the transparent images.

**Comment by chimzycash** [comment]
Awesome... 
Glad that you liked it... Would prepare all the files including PNG and Vector files for your use.

**Comment by mlibre** [comment]
Just added you in contributors :)
https://github.com/mlibre/healight#thanks-to-kind-contributors

**Comment by chimzycash** [comment]
@mlibre  Here is the Google Drive link containing the Vector master Files and the PNG files for your use.
https://drive.google.com/drive/folders/1goZzHxlLGRb-Lah_PZ0mZeZ1HdfRYma4?usp=sharing
