### ISSUE TITLE
Demo for Introducing project features and UI

### ISSUE THREAD

**Issue by MarshalOfficial** [mlibre/healight#2]
Hi bro, these days i saw lots of GitHub repositories in different topics and languages, it seems Healight needs a good online demo with demo admin user, it helps developers to easier understand what is this and features and power of this product, and it helps to more forks and stars and develop it to make it better and use in different places, for better world,
Regards,,

**Comment by mlibre** [comment]
Hi @MarshalOfficial :)
Yeh, I should.
Right now while I am improving the project, creating road-map and ..., in meanwhile, I am also making things more **automatical**. So by starting the app, the app will **build/repair** itself, including the **database**.
Also, I am making the **configuration** more **easy** to read and set.
After finishing all these I will make a **GitHub wiki** for documentation and etc..
I think If I lunch my own encyclopedia made by Healight (**English-Completed**), I can add it as a good example of what it can do.

**Comment by MarshalOfficial** [comment]
@mlibre Nice

**Comment by mlibre** [comment]
https://mlibre.github.io/healight/ :smiley:
